# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a0bd0f534d3e9000503cff5df1ac698685cfe228657f92ba70907ddee56bbc760e1bfee2eaefd9e3b011e61be5a96a6ab7da77af07ce5b069440e2e756c06f4a

test:
  secret_key_base: 5388296a489f05b65ba1cd91a68db82a8f1e6324c95fcc5139edce7d74b5c525510bd07fa895da503631750137b34eab689d00c781ee18fe580d831d859d4fb0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
